import Head from "next/head";
import { Inter } from "@next/font/google";
import { Layout } from "@/components";
import Link from "next/link";
import { FiArrowRight, FiBook } from "react-icons/fi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="bg-white dark:bg-gray-900 hero mt-8 mb-12">
          <div className="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
            <h1 className="mb-6 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
              We invest in the world’s potential
            </h1>
            <p className="mb-10 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">
              Here at Flowbite 🇲🇩 we focus on markets where technology, innovation, and capital can
              unlock long-term value and drive economic growth.
            </p>
            <div className="flex flex-col mb-8 lg:mb-16 space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
              <Link href="/signin" className="btn btn-primary text-base">
                Get Started
                <FiArrowRight className="ml-2 text-lg" />
              </Link>
              <Link href="/about" className="btn btn-outline text-base">
                <FiBook className="mr-2 text-lg" />
                Learn more
              </Link>
            </div>
            <div className="mockup-window border border-base-300">
              <div className="flex justify-center px-4 py-48 border-t border-base-300">Hello!</div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}
